datadir:  "/data/cephfs-2/unmirrored/groups/ritter/MR_processing/HCP-EP/derivatives_2026/"
rootdir: "/data/cephfs-1/work/groups/ritter/users/dada15_c/hcpep-analysis"
outdir: "/data/cephfs-1/scratch/groups/ritter/HCP-EP_analysis"

window_size: 30
step_size: 1

min_density: 0.1
max_density: 0.6
density_step: 0.05